# Created 2017-04-22 Sat 01:26
#+TITLE: Get-ChildItemColor
#+AUTHOR: Joon Ro
This provides a colored version of =Get-ChildItem= Cmdlet of PowerShell. It is
based on Tim Johnson's [[http://tasteofpowershell.blogspot.com/2009/02/get-childitem-dir-results-color-coded.html][script]]. In addition to the original functionality, it
provides:

- Better performance by using =Dictionary= objects instead of regular
  expressions
- Color support for =| Format-Wide= format (=ls= equivalent)
- Automatically compute number of columns for =| Format-Wide= format (thanks
  to [[https://github.com/gcollic][Guillaume Collic]])

* Install
** Install from PowerShellGallery
PowerShellGet is required, which is included in Windows 10 and WMF5. If you
are using PowerShell V3 or V4, you will need to install [[https://www.microsoft.com/en-us/download/details.aspx?id=49186][PowerShellGet]].

Then, you can simply run =Install-Module Get-ChildItemColor= (or
=Install-Module Get-ChildItemColor -Scope CurrentUser=).

** Install from GitHub
Clone the repo in your PowerShell Module folder
(=$ENV:UserProfile\Documents\WindowsPowerShell\Modules=).

#+BEGIN_SRC sh
git clone https://github.com/joonro/Get-ChildItemColor.git
#+END_SRC
* Usage
When you import the module:

#+BEGIN_SRC powershell
Import-Module Get-ChildItemColor
#+END_SRC

it will expose two functions, =Get-ChildItemColor= and =Get-ChildItemColorFormatWide=.

You can add aliases to these functions for convenience. For example, I have
the following in my =$PROFILE$= [fn:PathProfile]:

#+BEGIN_SRC powershell
Import-Module Get-ChildItemColor
 
Set-Alias l Get-ChildItemColor -option AllScope
Set-Alias ls Get-ChildItemColorFormatWide -option AllScope
#+END_SRC

So =l= yields colored output of =Get-ChildItem= and =ls= yields colored output
of =Get-ChildItem | Format-Wide=

[fn:PathProfile] =$ENV:UserProfile\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1=
* Authors
- [[http://github.com/joonro][Joon Ro]]
- This code is based on Tim Johnson's [[http://tasteofpowershell.blogspot.com/2009/02/get-childitem-dir-results-color-coded.html][script]] and also [[http://stackoverflow.com/users/153982/keith-hill][Keith Hill]]'s answer at
  [[http://stackoverflow.com/questions/3420731/][this]] Stack Overflow question.
* Changelog
** v0.5.2
- Published on PowerShellGallery
- Refactoring; separate out two functions
** v0.4.2
- Make it a PowerShell module
** v0.4.1
- Returns vanila =Get-Childitem= results for =DictionaryEntry= cases.
** v0.4.0
- Make function names consistent to the PowerShell naming convention (#8)
- Use parameters more consistently, =-Path= works with paths with spaces (#3),
  and =-Force= works (#9)
